### ISSUE TITLE
Can't work well in MIUI V5?

### ISSUE THREAD

**Issue by CodeingBoy** [MohammadAG/Xposed-Tinted-Status-Bar#110]
Seems 1.8.9.5 can't work well in MIUI V5(MIUI Version 4.8.9, Android Version 4.4.4, MI 2).It didn't work well at all.
1.8.9.3 is OK.

**Comment by daviduuang** [comment]
Same issue happened in MIUI V5 as "CodeingBoy".

## error log:

Sep 24, 2014 2:52:24 AM UTC
Loading Xposed v55 (for Zygote)...
Running ROM 'JZO54K' with fingerprint 'Xiaomi/mione_plus/mione_plus:4.1.2/JZO54K/4.9.19:user/release-keys'
Loading modules from /data/app/com.xad-1.apk
  Loading class com.main.MainHook
Loading modules from /data/app/de.xiaoxia.xstatusbarlunardate-1.apk
  Loading class de.xiaoxia.xstatusbarlunardate.Main
  Loading class de.xiaoxia.xstatusbarlunardate.Lockscreen
Loading modules from /data/app/pro.burgerz.wsm.mods.wsm_alarmtimefix-2.apk
  Loading class pro.burgerz.wsm.mods.wsm_alarmtimefix.AlarmTimeFix
[AlarmTimeFix] Hooking: com.android.server.ExtraAlarmManagerService.inPackageNameWhiteList(?)
[AlarmTimeFix] Done!
Loading modules from /data/app/com.oasisfeng.greenify-2.apk
  Loading class com.oasisfeng.greenify.pro.FrameworkPatch
  Loading class com.oasisfeng.greenify.pro.SettingsPatch
Loading modules from /data/app/com.mohammadag.colouredstatusbar-1.apk
  Loading class com.mohammadag.colouredstatusbar.ColourChangerMod
Loading modules from /data/app/net.mitchtech.xposed.macroexpand-2.apk
  Loading class net.mitchtech.xposed.XposedMacroExpand
XposedMacroExpand: prefs loaded.
Loading modules from /data/app/com.mohammadag.burnttoast-1.apk
  Loading class com.mohammadag.burnttoast.XposedMod
java.lang.NoSuchMethodError: com.android.systemui.statusbar.policy.Clock#updateClock()#exact
    at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:196)
    at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:146)
    at com.mohammadag.colouredstatusbar.ColourChangerMod.doClockHooks(ColourChangerMod.java:694)
    at com.mohammadag.colouredstatusbar.ColourChangerMod.handleLoadPackage(ColourChangerMod.java:260)
    at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
    at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
    at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
    at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:209)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:612)
    at android.app.ActivityThread.handleBindApplication(Native Method)
    at android.app.ActivityThread.access$1300(ActivityThread.java:137)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1262)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4819)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)
    at dalvik.system.NativeStart.main(Native Method)

---

And you can get related low-level system files(e.g. SystemUI.apk, framework.jar etc.)  from here: https://www.dropbox.com/sh/lm7ixm8hvyb1j90/AACTokq9DBoM4qU83nZxTLJna?dl=0

MIUI V5(MIUI v4.9.19, Android 4.1.2, XiaoMi 1S), Tinted Statusbar v1.8.9.5
(1.8.9.3 is OK)
